baseURL = "https://filiprafaj.github.io/nehop"
languageCode = "cs"
theme = "moments"
paginate = 10
paginatePath = '.'

[params]
    title = ""
    signature = ""
    cover = "https://raw.githubusercontent.com/filiprafaj/nehop/main/nehop.jpg"

    name = "Filip Rafaj"
    avatar = "/img/default_avatar.png"
