baseURL = "https://filiprafaj.github.io/nehop"
languageCode = "cs"
theme = "moments"
paginate = 10
paginatePath = '.'

[params]
    title = "NEHOP"
    signature = "Horolezecký oddíl Pelhřimov"
    cover = "https://raw.githubusercontent.com/filiprafaj/nehop/main/nehop.jpg"

    name = "Filip Rafaj"
    avatar = "/img/default_avatar.png"
