baseURL = "https://filiprafaj.github.io/nehop"
languageCode = "cs"
theme = "moments"
paginate = 10
paginatePath = '.'

[params]
    title = ""
    signature = ""
    cover = "https://raw.githubusercontent.com/filiprafaj/nehop/main/nehop_title.jpg"

    name = "NEHOP"
    avatar = "https://raw.githubusercontent.com/filiprafaj/nehop/main/nehop_profile.jpg"
